# Generated by Django 5.0.3 on 2024-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=45)),
                ('ingredients', models.TextField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/recipe')),
            ],
        ),
    ]
